danvbe_resman_admin:
    resource: "@DanvbeResmanBundle/Resources/config/routing/admin.yml"
    prefix: /admin

danvbe_resman_main:
    resource: "@DanvbeResmanBundle/Resources/config/routing/main.yml"
    prefix: /