parameters:
#    danvbe_resman.example.class: Danvbe\ResmanBundle\Example

services:
#    danvbe_resman.example:
#        class: %danvbe_resman.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
