<?php

namespace Danvbe\ResmanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConnectedResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConnectedResourceRepository extends EntityRepository
{
}
