<?php

namespace Danvbe\ResmanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceTypeRepository extends EntityRepository
{
    public function getAllNonPropertiesOrderedByNameQueryBuilder(){
        $q = $this->createQueryBuilder('rt')
            ->select('rt')
            ->where('rt.data_type is null')
            ->orderBy('rt.name');

        return $q;
    }
}
