<?php

namespace Danvbe\ResmanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResourceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceTypeRepository extends EntityRepository
{
    public function findAllOrderedByName(){

        return $this->getEntityManager()
            ->createQuery('select rt from DanvbeResmanBundle:ResourceType rt order by rt.name')
            ->getResult();
    }
}
