<?php

namespace Danvbe\ResmanBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ValueFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValueFileRepository extends EntityRepository
{
}
